version: '3'

services:
  web:
    build:
      context: .
      dockerfile: apache/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - database
      - phpmyadmin

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projecte
      MYSQL_USER: root
      MYSQL_PASSWORD: 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - database
